"""email password auth

Revision ID: 73d48561e5d4
Revises: 4d8811d3ee95
Create Date: 2026-08-21 17:43:13.168604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73d48561e5d4'
down_revision: Union[str, None] = '4d8811d3ee95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('requested_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_pwreset_user_used', 'password_reset_tokens', ['user_id', 'used_at'], unique=False)
    # NOTE: alembic autogenerate also proposed dropping an implicit FK from
    # otp_codes.user_phone -> users.phone (never reflected in the ORM model —
    # OtpCode.user_phone is a plain indexed string). It no longer makes sense
    # once users.phone is nullable, but its constraint name isn't stable
    # across SQLite vs Postgres reflection, so it's left as a follow-up for
    # whoever owns the Postgres schema rather than risking a fragile drop here.
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone', existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_index('ix_pwreset_user_used', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
